-- Migration 0003: No-op
-- The original_status and last_checked_at columns were consolidated into
-- migration 0001 during initial development (before any production deploy).
-- This file is kept to preserve migration numbering.
